In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# ENV SETUP AND DATA LOADING

In [0]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import svm
from sklearn.svm import SVC

In [0]:
train_data = pd.read_csv("/content/drive/My Drive/Shravani_Spring2020/paper_data_train.csv")
val_data = pd.read_csv("/content/drive/My Drive/Shravani_Spring2020/paper_data_dev.csv")
test_data = pd.read_csv("/content/drive/My Drive/Shravani_Spring2020/paper_data_test.csv")

In [0]:
train_data.head()

paper_id  ... accepted
0  304.pdf  ...     True
1  305.pdf  ...     True
2  306.pdf  ...     True
3  307.pdf  ...     True
4  308.pdf  ...     True

[5 rows x 19 columns]

In [0]:
final_train = train_data
final_test = pd.concat([val_data, test_data], ignore_index=True)

Bert_train = final_train.iloc[0:, [0,1,18]]
print(Bert_train.shape)
Bert_train.head()

Bert_test = final_test.iloc[0:, [0,1,18]]
print(Bert_test.shape)
Bert_test.head()

(349, 3)
(77, 3)


paper_id                        feature_extraction_encoding  accepted
0  316.pdf  [0.3783118724822998, -0.056981366127729416, -0...      True
1  325.pdf  [0.40649187564849854, -0.03665460646152496, -0...      True
2  328.pdf  [0.48881033062934875, -0.07407109439373016, -0...      True
3  340.pdf  [0.45297518372535706, -0.05653221160173416, 0....      True
4  350.pdf  [0.43022093176841736, -0.07531613111495972, -0...      True

# DATA CLEANING

In [0]:
 def create_array(vect_temp):
  n = len(vect_temp)
  vect_list = []

  i = 1 
  while(i<(n-1)):
    str_temp = ""
    while(i<(n-1) and vect_temp[i]!=','):
      str_temp = str_temp + vect_temp[i]
      i = i+1
    vect_list.append(float(str_temp))
    i = i+2
  return np.array(vect_list)

rows, cols = Bert_train.shape
features_array = np.random.randn(rows, 768)
for i in range(0, rows):
  features_array[i] = create_array(Bert_train.iloc[i,1])

std_scale = StandardScaler()
std_scale.fit(train)
train = pd.DataFrame(data=features_array)
train = std_scale.transform(train)

rows, cols = Bert_test.shape
features_array = np.random.randn(rows, 768)
for i in range(0, rows):
  features_array[i] = create_array(Bert_test.iloc[i,1])

test = pd.DataFrame(data=features_array)
test = std_scale.transform(test)

# PCA


In [0]:
pca = PCA(n_components=100)
pca_applied_data = pca.fit_transform(train)
var_ratio = pca.explained_variance_ratio_
i = 0
variance = 0
for ele in var_ratio:
  variance = variance + ele
  i = i+1
  if(variance>=0.85):
    break
num_components = i
print(num_components)

pca = PCA(n_components=num_components)
pca.fit(train)
pca_applied_data = pca.transform(train)
pca_applied_data = pd.DataFrame(data = pca_applied_data)
pca_applied_data['paper_id'] = Bert_train['paper_id']
pca_applied_data['accepted'] = Bert_train['accepted']
pca_applied_data = pca_applied_data[ ['paper_id'] + [ col for col in pca_applied_data.columns if col != 'paper_id' ] ]
print(pca_applied_data.shape)
train_fin = pca_applied_data
train_fin.head()

58
(349, 60)


paper_id         0         1  ...        56        57  accepted
0  304.pdf -0.489618  0.406951  ... -0.040229  0.144672      True
1  305.pdf -0.378550 -0.026607  ...  0.099567  0.103073      True
2  306.pdf -0.162822  0.438935  ...  0.030463 -0.073082      True
3  307.pdf  1.209099 -0.095308  ... -0.058427  0.008692      True
4  308.pdf  0.206198  0.407238  ... -0.141223  0.194643      True

[5 rows x 60 columns]

In [0]:
pca_applied_data = pca.transform(test)
pca_applied_data = pd.DataFrame(data = pca_applied_data)
pca_applied_data['paper_id'] = Bert_test['paper_id']
pca_applied_data['accepted'] = Bert_test['accepted']
pca_applied_data = pca_applied_data[ ['paper_id'] + [ col for col in pca_applied_data.columns if col != 'paper_id' ] ]
print(pca_applied_data.shape)
test_fin = pca_applied_data
test_fin.head()

(77, 60)


paper_id         0         1  ...        56        57  accepted
0  316.pdf  1.435818 -0.348435  ...  0.075851 -0.013066      True
1  325.pdf -1.071523  0.556425  ...  0.002623 -0.127876      True
2  328.pdf  0.615214  0.456142  ...  0.178021  0.095584      True
3  340.pdf -0.807391  0.126312  ... -0.006118 -0.113358      True
4  350.pdf  0.304558  0.559218  ...  0.018323  0.020452      True

[5 rows x 60 columns]

# TRAIN-TEST SPLIT

In [0]:
x_indices = []
for i in range(1,59):
  x_indices.append(i)

Xtrain = train_fin.iloc[0:,x_indices]
ytrain = train_fin.iloc[0:,59]

Xtest = test_fin.iloc[0:,x_indices]
ytest = test_fin.iloc[0:,59]

## SVM

In [0]:
parameters = {'kernel':('rbf', 'poly', 'sigmoid'), 'C':range(1,100)}
svc = SVC()
svm_clf = GridSearchCV(svc, parameters, verbose=1, cv=10)
svm_clf.fit(Xtrain, ytrain)

Fitting 10 folds for each of 297 candidates, totalling 2970 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 2970 out of 2970 | elapsed:   45.1s finished


GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': range(1, 100),
                         'kernel': ('rbf', 'poly', 'sigmoid')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [0]:
print(svm_clf.best_estimator_)
print(svm_clf.best_params_)
print(svm_clf.best_score_)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
{'C': 1, 'kernel': 'poly'}
0.6047058823529412


In [0]:
scores = cross_val_score(svm_clf, Xtrain, ytrain, cv=10)

In [0]:
scores.mean()

0.5701680672268907

In [0]:
clf_predictions = svm_clf.predict(Xtest)
print(confusion_matrix(ytest,clf_predictions))
print(classification_report(ytest,clf_predictions))

[[41  3]
 [28  5]]
              precision    recall  f1-score   support

       False       0.59      0.93      0.73        44
        True       0.62      0.15      0.24        33

    accuracy                           0.60        77
   macro avg       0.61      0.54      0.48        77
weighted avg       0.61      0.60      0.52        77



**ENVIRONMENT SETUP**

In [0]:
pip install prince

In [0]:
import pandas as pd
import numpy as np
import prince
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,cross_val_score
import pickle
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.decomposition import PCA
from tqdm import tqdm

**DATA SETUP**

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
train_data_df = pd.read_pickle("/content/drive/My Drive/ML/paper_data_train.pkl")
train_data_features = train_data_df.drop(columns=['paper_id','feature_extraction_encoding','tfidf_encoding','accepted'])
test_data_df = pd.read_pickle("/content/drive/My Drive/ML/paper_data_test.pkl")
test_data_features = test_data_df.drop(columns=['paper_id','feature_extraction_encoding','tfidf_encoding','accepted'])

In [0]:
#TRAIN DATA
X_train = np.vstack(train_data_df['feature_extraction_encoding'].values.tolist())
y_train = np.asarray([1 if item==True else 0 for item in list(train_data_df['accepted'])])

#TEST DATA
X_test = np.vstack(test_data_df['feature_extraction_encoding'].values.tolist())
y_test = np.asarray([1 if item==True else 0 for item in list(test_data_df['accepted'])])

**DIMENSION REDUCTION**

In [0]:
bert_vector_size = X_train.shape[1]+1
for i in tqdm(range(2,bert_vector_size)):
    pca = prince.PCA(n_components=i)
    pca = pca.fit(X_train)
    retained_variance = sum(pca.explained_inertia_)
    if retained_variance > 0.95:
        break
print("\nVariance retained for ",i," components = ",retained_variance)
X_train_reduced = pca.fit_transform(X_train)
X_test_reduced = pca.transform(X_test)


 17%|█▋        | 134/767 [00:05<00:26, 23.45it/s]



Variance retained for  137  components =  0.9502651618209814




---
**LOGISTIC REGRESSION**

---




In [0]:
from sklearn.linear_model import LogisticRegression
parameters = {'solver':['liblinear'],'penalty':('l1', 'l2', 'elasticnet'), 'C':range(1,50), 'fit_intercept':(True, False), 'class_weight':(None, 'balanced')}
bert_lr = LogisticRegression(max_iter=700,warm_start=True)
clf_bert_lr = GridSearchCV(bert_lr, param_grid=parameters, verbose=1, cv=3, n_jobs=-1)
clf_bert_lr.fit(X_train_reduced, y_train)

Fitting 3 folds for each of 588 candidates, totalling 1764 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 216 tasks      | elapsed:    5.7s
[Parallel(n_jobs=-1)]: Done 1416 tasks      | elapsed:   58.9s
[Parallel(n_jobs=-1)]: Done 1764 out of 1764 | elapsed:  1.3min finished


GridSearchCV(cv=3, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=700, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=True),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': range(1, 50), 'class_weight': (None, 'balanced'),
                         'fit_intercept': (True, False),
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ['liblinear']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, 

In [0]:
filename = 'bert_lr_model.sav'
pickle.dump(clf_bert_lr, open(filename, 'wb'))

In [0]:
best_params = clf_bert_lr.best_params_
val_score = clf_bert_lr.best_score_
print(best_params)
print("VALIDATION SCORE =", val_score)

{'C': 43, 'class_weight': None, 'fit_intercept': True, 'penalty': 'l1', 'solver': 'liblinear'}
VALIDATION SCORE = 0.5644464092739955


In [0]:
clf_predictions = clf_bert_lr.predict(X_test_reduced)
print(confusion_matrix(y_test,clf_predictions))
print(classification_report(y_test,clf_predictions))

[[23 21]
 [20 13]]
              precision    recall  f1-score   support

           0       0.53      0.52      0.53        44
           1       0.38      0.39      0.39        33

    accuracy                           0.47        77
   macro avg       0.46      0.46      0.46        77
weighted avg       0.47      0.47      0.47        77





---
**RANDOM FOREST**

---




In [0]:
from sklearn.ensemble import RandomForestClassifier
n_estimators = [30, 40, 50, 60, 100]
max_depth = [15, 20, 25, 30]
min_samples_split = [2, 5, 10, 15, 20]
min_samples_leaf = [1, 2, 5]
hyperF = dict(n_estimators = n_estimators, max_depth = max_depth,  
              min_samples_split = min_samples_split, 
             min_samples_leaf = min_samples_leaf)

bert_rf = RandomForestClassifier()
clf_bert_rf = GridSearchCV(bert_rf, hyperF, cv = 5, verbose = 1, n_jobs = -1)
clf_bert_rf.fit(X_train_reduced, y_train)

Fitting 5 folds for each of 300 candidates, totalling 1500 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   31.2s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-1)]: Done 446 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-1)]: Done 796 tasks      | elapsed:  8.9min
[Parallel(n_jobs=-1)]: Done 1246 tasks      | elapsed: 13.9min
[Parallel(n_jobs=-1)]: Done 1500 out of 1500 | elapsed: 16.7min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [0]:
filename = 'bert_rf_model.sav'
pickle.dump(clf_bert_lr, open(filename, 'wb'))

In [0]:
best_params = clf_bert_rf.best_params_
val_score = clf_bert_rf.best_score_
print(best_params)
print("VALIDATION SCORE =", val_score)

{'max_depth': 25, 'min_samples_leaf': 5, 'min_samples_split': 15, 'n_estimators': 50}
VALIDATION SCORE = 0.6247619047619047


In [0]:
clf_predictions = clf_bert_rf.predict(X_test_reduced)
print(confusion_matrix(y_test,clf_predictions))
print(classification_report(y_test,clf_predictions))

[[42  2]
 [28  5]]
              precision    recall  f1-score   support

           0       0.60      0.95      0.74        44
           1       0.71      0.15      0.25        33

    accuracy                           0.61        77
   macro avg       0.66      0.55      0.49        77
weighted avg       0.65      0.61      0.53        77

